---
name: docker-broker

instance_groups:
- name: docker
  azs: [z1]
  instances: 1
  persistent_disk: 65536
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: docker
    release: docker
  - name: cf-containers-broker
    release: docker
    provides:
      cf-containers-broker:
        as: servicebroker
        shared: true
    properties:
      username: broker
      password: ((broker_password))
      cookie_secret: ((broker_cookie_secret))
      max_containers: 20
      services: []

variables:
- name: broker_password
  type: password
- name: broker_cookie_secret
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: docker
  version: 30.0.0-rc.7
  url: https://github.com/cloudfoundry-community/docker-boshrelease/releases/download/v30.0.0-rc.7/docker-30.0.0-rc.7.tgz
  sha1: 4badb303131906a1fec3e2ed6eaaa39e66a55b56
