---
name: docker-broker

instance_groups:
- name: subway
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: subway-broker
    release: cf-subway

- name: docker
  azs: [z1,z2,z3]
  instances: 3
  persistent_disk: 65536
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"

  - name: cf-containers-broker
    release: docker
    provides:
      cf-containers-broker:
        as: servicebroker
        shared: true
    properties:
      username: broker
      password: ((broker-password))
      cookie_secret: ((broker-cookie-secret))
      max_containers: 20
      services: []

- name: sanity-test
  azs: [z1]
  lifecycle: errand
  instances: 1
  persistent_disk: 65536
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sanity-test-broker
    release: docker

variables:
- name: broker-password
  type: password
- name: broker-cookie-secret
  type: password
- name: docker-ca
  type: certificate
  options:
    is_ca: true
    common_name: dockerCA
- name: docker-tls
  type: certificate
  options:
    ca: docker-ca
    common_name: docker
    extended_key_usage:
    - client_auth

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: cf-subway
  version: 3.0.0
  url: https://bosh.io/d/github.com/cloudfoundry-community/cf-subway-boshrelease?v=3.0.0
  sha1: 4e241dff1552e626e0677941da69944eafeca1ff
- name: docker
  version: 30.0.0-rc.21
  url: https://github.com/cloudfoundry-community/docker-boshrelease/releases/download/v30.0.0-rc.21/docker-30.0.0-rc.21.tgz
  sha1: 0fc0da5857884a7a98cb537540a88ef9d2e9efa3
